### PR TITLE
Correct and simplify Replist::add and Replist::find

### PR DESCRIPTION
**Pull request by changwoo**
Fixes hunspell/hunspell#480

### CODE REVIEW

**Comment by changwoo** [comment]
OK, so I reverted the Replist::find change and corrected (and simplified) the sorting code to respect the linear-search-friendly list order.

**Comment by changwoo** [comment]
Hmm.  I admit it doesn't work in some cases. Keeping this linear-search friendly list order and doing binary search conflict each other.

**Comment by dimztimz** [comment]
This seems OK on first look. So you cleaned up the code from the commit I pointed in the issue?

> Hmm. I admit it doesn't work in some cases. Keeping this linear-search friendly list order and doing binary search conflict each other.

What is it that is not working?

**Comment by dimztimz** [comment]
For completeness can you manually test the minimal case you pointed in an older issue #441 since you touched on the same code related to that issue.

**Comment by changwoo** [comment]
> This seems OK on first look. So you cleaned up the code from the commit I pointed in the issue?

Yes I did.

> > Hmm. I admit it doesn't work in some cases. Keeping this linear-search friendly list order and doing binary search conflict each other.
> 
> What is it that is not working?

For example, in the "sorted" list like this,

```
[0] = a
[1] = ba
[2] = b
```

1. Find "b"
2. During binary search between 0...2, the first pivot is ```[1] = ba```, 
3. strncmp("b", "ba", 2) < 0, so the next round is 0...0, so "b" can't found in this case.

Of course a different comparison (with additional substring check) will work, but I don't think it is worth to keep the linear-search friendly sort order in the cost of slow searching.

**Comment by changwoo** [comment]
> For completeness can you manually test the minimal case you pointed in an older issue #441 since you touched on the same code related to that issue.

I can't find the same code between this and #441 (which has already been merged in 1.6.0). Do you mean other issue?

**Comment by dimztimz** [comment]
> I can't find the same code between this and #441 (which has already been merged in 1.6.0). Do you mean other issue?
I meant #411. Sorry.

**Comment by dimztimz** [comment]
> For example, in the "sorted" list like this,
> ...

Since I see you pushed three commits (you probably did git reset and then force push), the last one I see seems OK to me. The example you show me was probably for the old behavior. With the changes now, the sort order should be `a, b, ba`.

ATM with your change is Korean working again? Is Nepali working? Both the Nepali unit test and the unit test you added pass.

Should I merge because according to me everything is all right?


The algo INCLUDING this patch is the following:

Lets say the input is `ZXYbacZXY`. Our list of search strings contains:

```
...
ba
bac
bau
...
```

The pointer `word` eventually comes at the b in the `RepList::conv()` method
```
ZXYbacZXY
   ^
   char * word
```

The binary search midpoint at some point can hit equality either at `ba` or `bac`. If it hits at `ba`, we will linearly search up to `bac`. If it hits at `bac` then we are ok. I don't see any falacy in the algo right now.

**Comment by dimztimz** [comment]
OK I found a solution. Once a midpoint has made a match, remember it and continue the binary search in the higher half (right half). The last match will be returned.

**Comment by dimztimz** [comment]
I merged this with my own fix. Please check if Korean works now with the master branch.

**Comment by changwoo** [comment]
It works great. Thanks.

**Pull request merged**
