### PR TITLE
Hunspell Dockerfile

### PR DESCRIPTION
**Pull request by loretoparisi**
I have created a `Dockerfile` for hunspell to take advantage of cached docker layers and to execute hunspell build and run in different environments.

To build the docker image from the Dockerfile folder you do

```
docker build -t hunspell .
```

This will build all layers, cache each of them with a opportunist caching of git repositories for hunspell and dictionaries stable branches.

Then to run the container in interactive mode (bash) you do

```
docker run --rm -it --name hunspell hunspell bash
```

resulting in

```
$ docker run --rm -it --name hunspell hunspell2 bash
root@27882a6508a7:~# echo "hallo how are yu?" | hunspell
Hunspell 1.5.3
& hallo 10 0: hall, halo, halloo, hallow, hello, halls, Gallo, hall o, Hall, Halon
*
*
& yu 15 14: yew, y, u, you, yum, yup, yuk, ye, ya, nu, yr, yo, cu, yd, mu

root@27882a6508a7:~# 
```

Those instruction should be added to the `README.md` in a `Docker section` (contribution mention will be glad).

### CODE REVIEW

**Comment by dimztimz** [comment]
Wait a minute, what is this?

Why is this needed, seems like it is adding unnecessary complexity.

**Comment by dimztimz** [comment]
Hunspell is already included in the package managers of major gnu/linux distributions so that is a probably the best way to install it. No need for docker.

Docker may be a modern thing but that means really nothing.

**Comment by loretoparisi** [comment]
@dimztimz yes it's a point of view of corse 🎱

**Comment by dimztimz** [comment]
Why don't you put this file in the docker-library repo. That seems more appropriate.

From my point of view Docker is just another way to package software, like .deb, .rpm etc. Each GNU/Linux distribution has its own repository that keeps scripts that make those packages. Similarly there should be some dockerfile database.

**Comment by loretoparisi** [comment]
Done https://hub.docker.com/r/loretoparisi/hunspell/ have a nice day!

**Pull request closed without merging**
