### PR TITLE
Add Tajik Language

### PR DESCRIPTION
**Pull request by Ibragimov**

### CODE REVIEW

**Comment by dimztimz** [comment]
Seems to me like a very incomplete translation. 

You should note that this is not related to spellchecker but only to the command line interface of hunspell.

**Comment by Ibragimov** [comment]
It is now 50% and growing... Please, receive updated file attached to this comment
[tg.zip](https://github.com/hunspell/hunspell/files/867602/tg.zip)

**Comment by dimztimz** [comment]
I will merge it once you finish it.

**Comment by Ibragimov** [comment]
Completed! It was easy. Please, merge.
[tg.zip](https://github.com/hunspell/hunspell/files/867755/tg.zip)

**Comment by dimztimz** [comment]
Can you add it as a commit and then push it?

**Pull request closed without merging**
