### PR TITLE
add missing visibility macros

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by dimztimz** [comment]
IIRC these things were intentionally removed and the Pimpl idiom was implemented so the only public thing is the class Hunspell.

**Comment by phajdan** [comment]
@jeroen Thanks for the PR. Could you elaborate on what are you trying to do? Consider filing an issue about that.

**Comment by jeroen** [comment]
We had an complicated [issue](https://github.com/ropensci/hunspell/issues/21) with the R bindings causing a crash due to conflicting symbol names in an IDE that also includes libhunspell. I was able to [solve](https://github.com/ropensci/hunspell/commit/0acde4f6cd115a68da6f75ca8d9df505b661c008) the problem patching our bindings to use:

```c
define LIBHUNSPELL_DLL_EXPORTED __attribute__((__visibility__("hidden")))
```
Thereby libhunspell symbols are hidden, and only the functions needed by our bindings are explicitly made visible. This prevents symbol conflicts when the shared library is loaded in a process which has it's own copy of libhunspell (but a different version).

Yes this solution would give compiler warnings due to some classes with `LIBHUNSPELL_DLL_EXPORTED` and some without. Only after [adding](https://github.com/ropensci/hunspell/commit/0acde4f6cd115a68da6f75ca8d9df505b661c008) the macro consistently to each of the classes, the library would compile with hidden libhunspell symbols, and the crashes were resolved.

**Comment by phajdan** [comment]
My understanding is that meaning of LIBHUNSPELL_DLL_EXPORTED and __attribute__((__visibility__("hidden"))) are opposite.

Is this possibly a problem with unexpected default visibility?

**Comment by dimztimz** [comment]
@jeroen concerning the bug you had with IDE.

The way libhunspell is build is with `attribute((visibility("default")))` set on the public methods and classes (`LIBHUNSPELL_DLL_EXPORTED` rewrites to **default visibility**, not to hidden, see the file `hunvisapi.h`). Additionally on the compiler `-fvisibility=hidden` is passed which makes hidden visibility on all methods that don't have explicit visibility declaration. This setup is documented here https://gcc.gnu.org/wiki/Visibility

In your build you don't use our build system, nor you use the system installed hunspell which may led to this bug. The bug probably appears because the IDE uses older version of hunspell where pimpl idiom was not used and many classes were marked as visible AND you build the new version without `fvisibility=hidden`.

What you did in the fix is that you completely hide your libhunspell.

So to properly fix this in your code, please revert the changes you posted. and do one of either:

1. Build libhunspell with the mentioned compiler flags, OR
2. Add a new macro LIBHUNSPELL_DLL_HIDDEN and add the prefix to the same classes that you mentioned in the change, but keep LIBHUNSPELL_DLL_EXPORTED
3. Hope that 1 or 2 will work. Can't promise anything.

Or just leave everything as it is now because it works somehow, via magic. Keep the patches you made local to opensci. If I apply this patch here I will make the library unusable for other users, because I will hide everything, according to GCC docs.

**Pull request closed without merging**
