### PR TITLE
Fix to prevent possible index out of range error

### PR DESCRIPTION
**Pull request by aarondandy**
I can't find any tests that cover this part of the code but the error and fix appear to be fairly obvious. Because there is not coverage please review carefully!

### CODE REVIEW

**Comment by PanderMusubi** [comment]
Can we add a test for this?

**Comment by aarondandy** [comment]
I may be able to take some time to read about Hungarian in a few weeks but if somebody already understands what this logic is doing, please go for it.

**Comment by aarondandy** [comment]
I have tried and failed at my quick attempt for coverage and failed. I may try again later if I can determine how to add new tests to the project if I can find the time to re-read the docs on the subject.

**Comment by caolanm** [comment]
looks good to me

**Pull request merged**
