### PR TITLE
Compiling issues under MSVC

### PR DESCRIPTION
**Pull request by LiMinggang**

### CODE REVIEW

**Comment by phajdan** [comment]
Thanks for the contribution!

Please note our automated CI tests are failing - please take a look at the logs and make sure not to break e.g. gcc on Linux.

Also curious: could you document the errors this change is fixing? Consider also mentioning the version of MSVC.

**Comment by PanderMusubi** [comment]
@LiMinggang Would you please like to test of [Nuspell](https://github.com/hunspell/nuspell) (the pure C++ successor of Hunspell) also builds with MSVC in your environment, see also https://github.com/hunspell/nuspell/issues/19 Thanks

**Comment by LiMinggang** [comment]
@PanderMusubi Was nuspell using C++ 11?

**Comment by LiMinggang** [comment]
@PanderMusubi Opened an issue for compiling errors

**Pull request closed without merging**
