### PR TITLE
filemgr get encapsulated

### PR DESCRIPTION
**Pull request by m-o-s-t-a-f-a**
Hi

I changed the filemgr object in order to make it more encapsulated.
It helps to reduce the code and debug it more easily.

please check it and let me know if you have any question about my changes.
I checked it with English and Persian dictionaries.

### CODE REVIEW

**Comment by dimztimz** [comment]
I don't think that refactoring the current codebase is productive. It is hard to read, too much mixed C with C++. Instead focus should be more on a rewrite, with using old pieces of code where appropriate and writing new when the old is too unclear.

**Comment by m-o-s-t-a-f-a** [comment]
It's not a big changes and it can be ignored. I just tried to make it more objective. 
The whole idea is that FileMgr can be responsible for chomping and trimming input data. 
Also it can internally handle comment lines as well as empty lines.

Let me know if you are agree with this idea. otherwise you can ignore this change.

**Comment by m-o-s-t-a-f-a** [comment]
If the idea is agreed, I can fix issues cross-platform compiling.

**Comment by dimztimz** [comment]
The 1.5 branch should only be for bugfixes. No refactoring there. If this change fixes bugs then it can be accepted.

If you are interested in making the code better, more readble etc. , then you can contribute to version 2.0. Version 2 should practically start with #409.

**Comment by m-o-s-t-a-f-a** [comment]
so better to postpone this change till porting to version 2.0. 
Please let me whenever you want to do it. the I can move this change there. 

Thanks

**Comment by dimztimz** [comment]
If you are still interested in contributing see the folder src/hunspell2 which is complete rewrite.  Closing this.

**Comment by m-o-s-t-a-f-a** [comment]
Hi

You mean I should move my code there? src/hunspell2 ?


Sincerely Yours
*,*Mostafa

**Comment by dimztimz** [comment]
No. Hunspell 2 code is incompatible. I meant if you are generally interested, look there.

**Comment by m-o-s-t-a-f-a** [comment]
ok. I will do.


Sincerely Yours
*,*Mostafa

**Pull request closed without merging**
