### PR TITLE
compile error caused by sublanguage with same integer value.

### PR DESCRIPTION
**Pull request by plicease**
I am getting a compile error on the gcc for windows.  The proposed patch fixes the problem for me.  Please let me know if I can help in providing details or testing alternate fixes.

```
gcc -c -DLOCALEDIR=\"/usr/local/share/locale\" -DLOCALE_ALIAS_PATH=\"/usr/local/share/locale\"
BLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/usr/local/lib\" -DNO_XMALLOC -Dset_relocation_pr
CONV=1 -DHAVE_CONFIG_H -I. -I. -I..  -g -O2 -fvisibility=hidden  localename.c
localename.c: In function '_nl_locale_name_default':
localename.c:1390:4: error: duplicate case value
    case SUBLANG_SINDHI_AFGHANISTAN: return "sd_AF";
    ^
localename.c:1389:4: error: previously used here
    case SUBLANG_SINDHI_PAKISTAN: return "sd_PK";
    ^
makefile:215: recipe for target 'localename.o' failed
gmake[2]: *** [localename.o] Error 1
gmake[2]: Leaving directory 'n:/home/ollisg/dev/hunspell/intl'
makefile:531: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory 'N:/home/ollisg/dev/hunspell'
makefile:438: recipe for target 'all' failed
gmake: *** [all] Error 2
                                                                     all' failedgmake: *** [all] Error 2rsive' failedgmake[1]: *** [all-recursive] Error 1gmake[1]: Leaving directory 'N:/home/ollisg/dev/hunspell'makefile:438: recipe for target 'all' failedgmake: *** [all] Error 2ence to `_imp___ZN8HunspellD1Ev'Hunspell.o:Hunspell.c:(.text+0x1637): undefined reference to `_imp___ZN8HunspellC1EPKcS1_S1_'Hunspell.o:Hunspell.c:(.text+0x1637): undefined reference to `_imp___ZN8HunspellC1EPKcS1_S1_'^ZN:\home\ollisg\perl5\strawberry\x86\5.22.0\lib\perl5\Alien\Hunspell>6-w64-mingw32\lib\libkernel32.a" "N:\lang\perl\strawberry\x86\5.22.0\c\i686-w64-mingw32\lib\libuser32.a" "N:\lang\perl\strawberry\x86\5.22.0\c\i686-w64-mingw32\lib\libgdi32.a" "N:\lang\perl\strawberry\x86\5.22.0\c\i686-w64-mingw32\lib\libwinspool.a" "
```

```
sh-3.1$ gcc --version
gcc.exe (i686-posix-sjlj, built by strawberryperl.com project) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### CODE REVIEW

**Comment by phajdan** [comment]
Whoa. This is weird. I'd like to understand this better before accepting the patch.

From localename.c:
```c
# ifndef SUBLANG_SINDHI_PAKISTAN
# define SUBLANG_SINDHI_PAKISTAN 0x01
# endif
# ifndef SUBLANG_SINDHI_AFGHANISTAN
# define SUBLANG_SINDHI_AFGHANISTAN 0x02
# endif
```

These do not appear to be defined from command line, or any other place in the source code:
```
$ git grep SUBLANG_SINDHI
intl/localename.c:# ifndef SUBLANG_SINDHI_PAKISTAN
intl/localename.c:# define SUBLANG_SINDHI_PAKISTAN 0x01
intl/localename.c:# ifndef SUBLANG_SINDHI_AFGHANISTAN
intl/localename.c:# define SUBLANG_SINDHI_AFGHANISTAN 0x02
intl/localename.c:        case SUBLANG_SINDHI_PAKISTAN: return "sd_PK";
intl/localename.c:        case SUBLANG_SINDHI_AFGHANISTAN: return "sd_AF";
```

Consider filing a bug with full and detailed steps to repro. I've never heard of strawberryperl.com before. Have you tried with some more common Windows toolchain - cygwin, mingw, or similar, and report back the results? That doesn't necessarily invalidate the bug, just gives us more data points.

**Comment by plicease** [comment]
The gcc that comes with strawberry is a variant of mingw.  Here is the header file these languages appear to be coming from:

```
xian-x86_64% ack SUBLANG_SINDHI
include/winnt.h
1152:#define SUBLANG_SINDHI_INDIA                      0x01
1153:#define SUBLANG_SINDHI_AFGHANISTAN                0x02
1154:#define SUBLANG_SINDHI_PAKISTAN                   0x02
```

I'd be happy to file a bug instead but it isn't obvious to me where these steps are enumerated.  I looked in the README file and the BUGS file but they did not offer any help.  Consider adding a CONTRIBUTING file, that will show up in the GitHub UI when people attempt to make a PR (example https://github.com/plicease/FFI-Platypus/issues/new).

**Comment by phajdan** [comment]
Ah, I see. This seems very similar to https://lists.gnu.org/archive/html/bug-gnu-utils/2007-02/msg00012.html and consistent with https://msdn.microsoft.com/en-us/library/dd318693(v=vs.85).aspx . The patch makes sense to me now, let me merge it.

**Comment by plicease** [comment]
I did some digging, and it appears that Strawberry uses the w64 variant for its gcc.  You can see the SUBLANG_SINDHI_AFGANISTAN and _PAKISTAN defined with the same value in the project's GIT got winnt.h here:

http://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/winnt.h#l1155

**Pull request merged**
